import React,{useEffect,useRef,useState} from 'react';
export default function GeometryPanel({map,latitude,longitude}) {
  const [drawing,setDrawing]=useState(false),[vertices,setVertices]=useState([]),[kind,setKind]=useState('land parcel'),[corner,setCorner]=useState('unknown'),[result,setResult]=useState(null),[error,setError]=useState('');
  const [source,setSource]=useState('user-drawn outline');
  const [footprints,setFootprints]=useState(null);const footprintRequest=useRef(0);
  useEffect(()=>{footprintRequest.current++;setFootprints(null);return()=>{footprintRequest.current++}},[latitude,longitude]);
  async function findFootprints(){const n=++footprintRequest.current;setFootprints({status:'checking nearby buildings',features:[]});try{const r=await fetch(`/footprints?latitude=${latitude}&longitude=${longitude}`);if(!r.ok)throw Error();const data=await r.json();if(n===footprintRequest.current)setFootprints(data)}catch{if(n===footprintRequest.current)setFootprints({status:'source unavailable',features:[],limits:'Draw or import an outline instead.'})}}
  useEffect(()=>{setDrawing(false);setVertices([]);setResult(null)},[latitude,longitude]);
  useEffect(()=>{if(!map)return;map.__measuring=drawing;const click=e=>{if(drawing){setVertices(v=>[...v,[e.lngLat.lng,e.lngLat.lat]]);setResult(null)}};map.on('click',click);if(drawing)map.getCanvas().style.cursor='crosshair';return()=>{map.off('click',click);map.__measuring=false;map.getCanvas().style.cursor=''}},[map,drawing]);
  useEffect(()=>{
    if(!map)return;
    const draw=()=>{const features=[];
      if(vertices.length>=3)features.push({type:'Feature',geometry:{type:'Polygon',coordinates:[[...vertices,vertices[0]]]},properties:{}});
      else if(vertices.length>=2)features.push({type:'Feature',geometry:{type:'LineString',coordinates:vertices},properties:{}});
      vertices.forEach(p=>features.push({type:'Feature',geometry:{type:'Point',coordinates:p},properties:{}}));
      const data={type:'FeatureCollection',features};
      if(map.getSource('measurement'))map.getSource('measurement').setData(data);
      else{map.addSource('measurement',{type:'geojson',data});map.addLayer({id:'measurement-fill',type:'fill',source:'measurement',filter:['==',['geometry-type'],'Polygon'],paint:{'fill-color':'#e8a12d','fill-opacity':.25}});map.addLayer({id:'measurement-line',type:'line',source:'measurement',filter:['!=',['geometry-type'],'Point'],paint:{'line-color':'#a8680b','line-width':3}});map.addLayer({id:'measurement-vertices',type:'circle',source:'measurement',filter:['==',['geometry-type'],'Point'],paint:{'circle-radius':5,'circle-color':'#a8680b'}})}
    };if(map.isStyleLoaded())draw();else map.once('load',draw);return()=>map.off('load',draw);
  },[map,vertices]);
  async function finish(){setDrawing(false);setError('');try{const r=await fetch('/measurements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({coordinates:vertices,area_kind:kind,corner_status:corner,source})});const body=await r.json();if(!r.ok)throw Error(typeof body.detail==='string'?body.detail:'Check coordinates');setResult(body)}catch(e){setError(e.message)}}
  async function importOutline(event){try{const file=event.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Use a single outline file smaller than 2 MB');let data=JSON.parse(await file.text());if(data.type==='FeatureCollection'){if(data.features.length!==1)throw Error('Import one property outline at a time');data=data.features[0]}const geometry=data.type==='Feature'?data.geometry:data;if(geometry.type!=='Polygon'||geometry.coordinates.length!==1)throw Error('Use a single Polygon without holes');const ring=geometry.coordinates[0];if(ring.length<4||ring.length>201||ring.some(p=>!Array.isArray(p)||p.length!==2||!p.every(Number.isFinite)))throw Error('Invalid polygon coordinates');if(JSON.stringify(ring[0])!==JSON.stringify(ring[ring.length-1]))throw Error('Polygon ring must be closed');setVertices(ring.slice(0,-1));setSource('Imported GeoJSON (user supplied): '+file.name);setDrawing(false);setResult(null);setError('');map.flyTo({center:ring[0],zoom:19})}catch(e){setError(e.message)}event.target.value=''}
  return <section><h2>Measure plot or building outline</h2><p>Zoom close, start drawing and click each boundary corner. Finish with at least three points.</p><p><a href={`https://www.google.com/maps/@${latitude},${longitude},19z/data=!3m1!1e3`} target="_blank" rel="noreferrer">Open Google Maps satellite at this location ↗</a></p>
    <button className="secondary" onClick={findFootprints}>Find open building outlines</button><p>{footprints?.status||'Outline lookup runs only when requested.'}</p>{footprints?.features.slice(0,5).map(f=><button className="secondary" key={f.properties.id} onClick={()=>{setVertices(f.geometry.coordinates[0].slice(0,-1));setKind('building footprint');setSource(f.properties.source);setDrawing(false);setResult(null)}}>Use mapped building {f.properties.id} · {f.properties.area_sqm} m²</button>)}{footprints&&<p className="muted">{footprints.limits}</p>}
    <label>Import one GeoJSON outline (Microsoft, OSM or parcel source)<input aria-label="Import outline" type="file" accept=".json,.geojson,application/json" onChange={importOutline}/></label>
    <label>Area kind<select aria-label="Area kind" value={kind} onChange={e=>{setKind(e.target.value);setResult(null)}}><option value="land parcel">Plot / land parcel</option><option value="building footprint">Building ground footprint</option></select></label>
    <label>Corner plot status<select value={corner} onChange={e=>{setCorner(e.target.value);setResult(null)}}><option value="unknown">Unknown</option><option value="user confirmed corner">I confirm it is a corner plot</option><option value="user confirmed not corner">I confirm it is not a corner plot</option></select></label>
    <button className="secondary" onClick={()=>{setDrawing(!drawing);setSource("user-drawn outline");setResult(null)}}>{drawing?'Pause drawing':'Draw boundary'}</button>{' '}<button className="secondary" disabled={!vertices.length} onClick={()=>{setVertices(v=>v.slice(0,-1));setResult(null)}}>Undo point</button>{' '}<button className="secondary" disabled={vertices.length<3} onClick={finish}>Finish & measure</button>{' '}<button className="secondary" onClick={()=>{setDrawing(false);setVertices([]);setResult(null)}}>Clear</button>
    <p role="status">{drawing?'Drawing: click boundary corners. ':''}{vertices.length} boundary points</p>{error&&<p role="alert">{error}</p>}
    {result&&<><h3>{result.area_sqm.toLocaleString()} m² · {result.area_sqft.toLocaleString()} ft²</h3><p>{result.area_kind} · perimeter {result.perimeter_m} m</p><p className="notice">Coordinate measurement of your outline. Boundary is unverified; this is not a survey. Footprint does not establish usable floor area.</p><a href={'/measurements/'+result.measurement_id} target="_blank" rel="noreferrer">Saved coordinates and measurement receipt</a></>}
  </section>;
}
