import React,{useEffect,useRef,useState} from 'react';
import EvidencePanel from './EvidencePanel';
import ImageryPanel from './ImageryPanel';
let loader;
function loadGoogle(key){if(window.google?.maps?.importLibrary)return Promise.resolve(window.google.maps);if(!loader)loader=new Promise((resolve,reject)=>{const script=document.createElement('script');const callback='avmGoogleReady';const timer=setTimeout(()=>{loader=null;reject(Error('Google Maps timed out. Use the open map or check API access.'))},15000);window[callback]=()=>{clearTimeout(timer);resolve(window.google.maps)};script.src='https://maps.googleapis.com/maps/api/js?'+new URLSearchParams({key,v:'weekly',loading:'async',libraries:'places',callback});script.onerror=()=>{clearTimeout(timer);loader=null;reject(Error('Google Maps could not load. Check the API key and enabled APIs.'))};document.head.appendChild(script)});return loader;}
export default function GooglePropertyMap({browserKey,onFallback}){
  const container=useRef(null),map=useRef(null),polygon=useRef(null),drawing=useRef(false),vertices=useRef([]);
  const [query,setQuery]=useState(''),[matches,setMatches]=useState([]),[selected,setSelected]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[isDrawing,setDrawing]=useState(false),[count,setCount]=useState(0),[measurement,setMeasurement]=useState(null),[areaKind,setAreaKind]=useState('land parcel'),[showReview,setShowReview]=useState(false);
  useEffect(()=>{let cancelled=false,listener;window.gm_authFailure=()=>{if(!cancelled)onFallback()};loadGoogle(browserKey).then(G=>{if(cancelled)return;map.current=new G.Map(container.current,{center:{lat:20,lng:10},zoom:3,mapTypeId:'hybrid',streetViewControl:true,mapTypeControl:true,fullscreenControl:true});polygon.current=new G.Polygon({map:map.current,strokeColor:'#d07d12',strokeWeight:3,fillColor:'#d07d12',fillOpacity:.2,clickable:false});listener=map.current.addListener('click',e=>{if(!drawing.current)return;vertices.current.push([e.latLng.lng(),e.latLng.lat()]);polygon.current.setPath(vertices.current.map(([lng,lat])=>({lat,lng})));setCount(vertices.current.length);setMeasurement(null)})}).catch(e=>setError(e.message));return()=>{cancelled=true;listener?.remove();polygon.current?.setMap(null)}},[browserKey]);
  function select(p){drawing.current=false;setDrawing(false);vertices.current=[];setCount(0);setMeasurement(null);polygon.current?.setPath([]);setSelected(p);setMatches([]);map.current.data.forEach(f=>map.current.data.remove(f));map.current.data.addGeoJson({type:'Feature',geometry:{type:'Point',coordinates:[p.lon,p.lat]},properties:{}});map.current.setCenter({lat:p.lat,lng:p.lon});map.current.setZoom(19)}
  async function search(e){e.preventDefault();setError('');setBusy(true);try{const G=await loadGoogle(browserKey);let found=[];try{const {Place}=await G.importLibrary('places');const response=await Place.searchByText({textQuery:query,fields:['displayName','formattedAddress','location'],maxResultCount:5});found=response.places.filter(p=>p.location).map(p=>({name:p.displayName,address:p.formattedAddress||p.displayName||query,lat:p.location.lat(),lon:p.location.lng()}))}catch{const response=await new G.Geocoder().geocode({address:query});found=response.results.map(p=>({name:p.formatted_address,address:p.formatted_address,lat:p.geometry.location.lat(),lon:p.geometry.location.lng()}))}if(found.length===1)select(found[0]);else{setMatches(found);if(!found.length)setError('No match. Include the city or country.')}}catch{setError('Google search unavailable. Check Places API/Geocoding API access or use the fallback map.')}finally{setBusy(false)}}
  function clear(){vertices.current=[];setCount(0);setMeasurement(null);polygon.current?.setPath([])}
  async function finish(){drawing.current=false;setDrawing(false);setError('');try{const response=await fetch('/measurements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({coordinates:vertices.current,area_kind:areaKind,source:'User outline drawn on Google Maps satellite/hybrid view'})});const result=await response.json();if(!response.ok)throw Error(typeof result.detail==='string'?result.detail:'Invalid boundary');setMeasurement(result)}catch(e){setError(e.message)}}
  return <><header><b className="brand">AVM / Google property search</b><button className="secondary" onClick={onFallback}>Use open map</button></header><main><section className="map-pane"><div ref={container} className="map"/><div className="search"><form onSubmit={search}><label>Address or business name<input aria-label="Google address search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="House, street, store, city…"/></label><button className="secondary" disabled={busy||!query.trim()}>{busy?'Searching…':'Search'}</button></form>{matches.map((p,i)=><button className="secondary" key={i} onClick={()=>select(p)}>{p.name}<br/>{p.address}</button>)}</div></section><aside><h1>{selected?.name||'Search any address or business'}</h1>{selected&&<p>{selected.address}</p>}{error&&<p role="alert">{error}</p>}<p>Use satellite/hybrid view and zoom close before drawing. Google Street View is available through the map’s native control where covered.</p><label>Area to measure<select value={areaKind} onChange={e=>{setAreaKind(e.target.value);setMeasurement(null)}}><option value="land parcel">Plot / land parcel</option><option value="building footprint">Building ground footprint</option></select></label><button className="secondary" disabled={!selected} onClick={()=>{drawing.current=!drawing.current;setDrawing(drawing.current)}}>{isDrawing?'Pause boundary':'Draw boundary'}</button>{' '}<button className="secondary" disabled={count<3} onClick={finish}>Finish & measure</button>{' '}<button className="secondary" onClick={clear}>Clear</button><p>{count} boundary points</p>{measurement&&<><h2>{measurement.area_sqm.toLocaleString()} m² · {measurement.area_sqft.toLocaleString()} ft²</h2><p>{measurement.area_kind} · perimeter {measurement.perimeter_m} m</p><p className="notice">Area of your selected outline. Boundary is unverified; footprint is not flat floor area.</p><a href={'/measurements/'+measurement.measurement_id} target="_blank" rel="noreferrer">Saved measurement coordinates</a></>}{selected&&<button className="secondary" onClick={()=>setShowReview(!showReview)}>{showReview?'Hide 3D/imagery review':'Open 3D/imagery review'}</button>}{selected&&showReview&&<ImageryPanel latitude={selected.lat} longitude={selected.lon}/>} {selected&&<EvidencePanel latitude={selected.lat} longitude={selected.lon} address={selected.address}/>}</aside></main></>;
}
